version: "3.9"
services:

  phpmyadmin:
    container_name: phpmyadmin_TagMedX
    image: phpmyadmin:5.2.1
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - network

  db:
    image: mysql:8.1.0
    container_name: db_TagMedX
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - DB:/var/lib/mysql     
      - ./DB/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - network

  backend:
    container_name: backend_TagMedX
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/app:ro
      - images:/images:rw
    ports:
      - 8000:8000
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db_TagMedX
      - DB_PORT=3306
      - DB_NAME=db
    networks:
      - network
    restart: on-failure

  # frontend:
  #   container_name: frontend_TagMedX
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./frontend/src:/app/src
  #     - /app/node_modules
  #   environment:
  #     NODE_ENV: development
  #   ports:
  #     - 80:3000
  #   networks:
  #     - network

volumes:
  DB:
  images:
networks:
  network:
